In [3]:
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine, text
import pymysql

print ("\n### Step 1: Dropping, Creating, and Populating Employees Table ###\n")

#Establish database connection
engine = create_engine("mysql+pymysql://jupyter:jupPassword@localhost/sakila", echo=False)

#Drop table if exists and create employees table
with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS employees;"))
    print("Table dropped.")

    conn.execute(text("""
    CREATE TABLE employees (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100),
        department VARCHAR(50),
        salary DECIMAL (10,2),
        join_date DATE
    );
    """))
    print("Table created.")

#insert sample data with explicit commit
    conn.execute(text("""
    INSERT INTO employees (name, department, salary, join_date) VALUES
    ('Allyson', 'Copywriting', 80000, '2026-06-17'),
    ('Cypress', 'IT', 70000, '2019-8-15'),
    ('Honey', 'Morale', 100000, '2026-1-31'),
    ('Isabel', 'Operations', 70000, '2020-12-31'),
    ('Katie', 'HR', 75000, '2022-11-5')
    """))

    conn.commit()
    print("Sample data inserted")

### Step 1: Dropping, Creating, and Populating Employees Table ###

Table dropped.
Table created.
Sample data inserted

In [4]:
print ("\n### Step 2: Loading Data from MySQL into Pandas DataFrame ###\n")

#1. Load data in Pandas DataFrame
df = pd.read_sql("SELECT * FROM employees;", engine)

#Display the final table
print("Data loaded successfully")
display(df)

### Step 2: Loading Data from MySQL into Pandas DataFrame ###

Data loaded successfully

   id     name   department    salary   join_date
0   1  Allyson  Copywriting   80000.0  2026-06-17
1   2  Cypress           IT   70000.0  2019-08-15
2   3    Honey       Morale  100000.0  2026-01-31
3   4   Isabel   Operations   70000.0  2020-12-31
4   5    Katie           HR   75000.0  2022-11-05

In [5]:
#2 Using Parameterized Queries for Security

query = "SELECT * FROM employees WHERE department =%s"
df_filtered = pd.read_sql(query, engine, params=("HR",))
print("Filtered data loaded using parameterized query.")
display(df_filtered)

Filtered data loaded using parameterized query.

   id   name department   salary   join_date
0   5  Katie         HR  75000.0  2022-11-05

In [7]:
# 3. Specifying Column Data types for Optimization
df_optimized = pd.read_sql("SELECT * FROM employees;", engine, dtype={"id": int, "salary": float})
print("Data loaded with sepcified column types")
display(df_optimized)

Data loaded with sepcified column types

   id     name   department    salary   join_date
0   1  Allyson  Copywriting   80000.0  2026-06-17
1   2  Cypress           IT   70000.0  2019-08-15
2   3    Honey       Morale  100000.0  2026-01-31
3   4   Isabel   Operations   70000.0  2020-12-31
4   5    Katie           HR   75000.0  2022-11-05

In [ ]:
print ("\n### Step 3: Filtering Aggregating, and Transforming Data ###\n")

#Filtering: Selecting employees with salary above 70000
df_filtered_salary = df[df["salary"] > 70000]
print("Employees with salary greater than 70000:")
display(df_filtered_salary)

#Filtering: Selecting employees who joined after 2020-01-01
df["join_date"] = pd.to_datetime(df["join_date"])
df_filtered_date = df[df["join_date"] > pd.to_datetime("2020-01-01")]
print("Employees who joined after 2020-01-01:")
display(df_filtered_date)