In [10]:
import pandas as pd
data_df = pd.read_csv("Data/hotel_bookings.csv")
print("the dataset contains", data_df.shape[0], "rows and", data_df.shape[1], "columns")
pd.set_option("display.max_columns", None)
data_df.head(7)

the dataset contains 119390 rows and 32 columns

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-07-03

In [11]:
data_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  str
dtypes: float64(4), int64(16), str(12)
memory usage: 29.1 MB

In [12]:
data_df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [49]:
#Looking for missing data per column
data_df.isnull().sum()

hotel                                 0
is_canceled                           0
lead_time                             0
arrival_date_year                     0
arrival_date_month                    0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
adults                                0
children                              0
babies                                0
meal                                  0
country                               0
market_segment                        0
distribution_channel                  0
is_repeated_guest                     0
previous_cancellations                0
previous_bookings_not_canceled        0
reserved_room_type                    0
assigned_room_type                    0
booking_changes                       0
deposit_type                          0
agent                             11800
days_in_waiting_list                  0
customer_type                         0
adr                                   0
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
reservation_status_year               0
reservation_status_month              0
reservation_status_day                0
res_week_of_year                      0
res_day_of_week                       0
res_weekday                           0
dtype: int64

In [15]:
data_df.drop("company", inplace=True, axis=1) #Dropping company column (axis 1)

In [16]:
data_df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [18]:
#looking at the values for the children comlumn
data_df["children"].value_counts()

children
0.0     110796
1.0       4861
2.0       3652
3.0         76
10.0         1
Name: count, dtype: int64

In [19]:
data_df.children = data_df.children.fillna(0)

In [20]:
data_df["country"].value_counts()

country
PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
       ...
NCL        1
KIR        1
SDN        1
ATF        1
SLE        1
Name: count, Length: 177, dtype: int64

In [21]:
#Dropping any row with an empty "country" cell.
data_df = data_df.dropna(subset = ["country"])

In [22]:
data_df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,394.0,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [24]:
#Fixing the index of the data from all the dropped rows.
data_df = data_df.reset_index(drop=True)
data_df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118897,City Hotel,0,23,2017,August,35,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,394.0,0,Transient,96.14,0,0,Check-Out,2017-09-06
118898,City Hotel,0,102,2017,August,35,31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,0,Transient,225.43,0,2,Check-Out,2017-09-07
118899,City Hotel,0,34,2017,August,35,31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,0,Transient,157.71,0,4,Check-Out,2017-09-07
118900,City Hotel,0,109,2017,August,35,31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,0,Transient,104.40,0,0,Check-Out,2017-09-07
118901,City Hotel,0,205,2017,August,35,29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [25]:
data_df["agent"].value_counts()

agent
9.0      31960
240.0    13871
1.0       7191
14.0      3639
7.0       3539
         ...
444.0        1
408.0        1
388.0        1
453.0        1
480.0        1
Name: count, Length: 332, dtype: int64

In [26]:
#Counts unique values for this column
data_df.agent.nunique()

332

In [27]:
data_df.isnull().sum()

hotel                                 0
is_canceled                           0
lead_time                             0
arrival_date_year                     0
arrival_date_month                    0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
adults                                0
children                              0
babies                                0
meal                                  0
country                               0
market_segment                        0
distribution_channel                  0
is_repeated_guest                     0
previous_cancellations                0
previous_bookings_not_canceled        0
reserved_room_type                    0
assigned_room_type                    0
booking_changes                       0
deposit_type                          0
agent                             16006
days_in_waiting_list                  0
customer_type                         0
adr                                   0
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
reservation_status_date               0
dtype: int64

In [28]:
##Duplicates

In [30]:
data_df.duplicated().sum()

np.int64(31965)

In [31]:
data_df.loc[data_df.duplicated(), :] # ':' displays all columns

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03
22,Resort Hotel,0,72,2015,July,27,1,2,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,0,Transient,84.67,0,1,Check-Out,2015-07-07
42,Resort Hotel,0,70,2015,July,27,2,2,3,2,0.0,0,HB,ROU,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,0,Transient,137.00,0,1,Check-Out,2015-07-07
137,Resort Hotel,1,5,2015,July,28,5,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,0,Transient,97.00,0,0,Canceled,2015-07-01
199,Resort Hotel,0,0,2015,July,28,7,0,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,109.80,0,3,Check-Out,2015-07-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118861,City Hotel,0,186,2017,August,35,31,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,0,Transient,126.00,0,2,Check-Out,2017-09-03
118864,City Hotel,0,63,2017,August,35,31,0,3,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03
118865,City Hotel,0,63,2017,August,35,31,0,3,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03
118866,City Hotel,0,63,2017,August,35,31,0,3,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03
118885,City Hotel,0,175,2017,August,35,31,1,3,1,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,0,Transient,82.35,0,1,Check-Out,2017-09-04

In [32]:
#Dropping duplicate rows

In [33]:
data_df.drop_duplicates(inplace=True, keep="first")

In [34]:
data_df.shape

(86937, 31)

In [35]:
##Datetime

In [36]:
data_df["reservation_status_date"] = pd.to_datetime(data_df["reservation_status_date"])

In [37]:
data_df.info()

<class 'pandas.DataFrame'>
Index: 86937 entries, 0 to 118901
Data columns (total 31 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           86937 non-null  str
 1   is_canceled                     86937 non-null  int64
 2   lead_time                       86937 non-null  int64
 3   arrival_date_year               86937 non-null  int64
 4   arrival_date_month              86937 non-null  str
 5   arrival_date_week_number        86937 non-null  int64
 6   arrival_date_day_of_month       86937 non-null  int64
 7   stays_in_weekend_nights         86937 non-null  int64
 8   stays_in_week_nights            86937 non-null  int64
 9   adults                          86937 non-null  int64
 10  children                        86937 non-null  float64
 11  babies                          86937 non-null  int64
 12  meal                            86937 non-null  str
 13  country                         86937 non-null  str
 14  market_segment                  86937 non-null  str
 15  distribution_channel            86937 non-null  str
 16  is_repeated_guest               86937 non-null  int64
 17  previous_cancellations          86937 non-null  int64
 18  previous_bookings_not_canceled  86937 non-null  int64
 19  reserved_room_type              86937 non-null  str
 20  assigned_room_type              86937 non-null  str
 21  booking_changes                 86937 non-null  int64
 22  deposit_type                    86937 non-null  str
 23  agent                           75073 non-null  float64
 24  days_in_waiting_list            86937 non-null  int64
 25  customer_type                   86937 non-null  str
 26  adr                             86937 non-null  float64
 27  required_car_parking_spaces     86937 non-null  int64
 28  total_of_special_requests       86937 non-null  int64
 29  reservation_status              86937 non-null  str
 30  reservation_status_date         86937 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(3), int64(16), str(11)
memory usage: 21.2 MB

In [39]:
#get year, month, and day
data_df["reservation_status_year"] =data_df["reservation_status_date"].dt.year
data_df["reservation_status_month"] =data_df["reservation_status_date"].dt.month
data_df["reservation_status_day"] =data_df["reservation_status_date"].dt.day
data_df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,reservation_status_year,reservation_status_month,reservation_status_day
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015,7,1
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015,7,1
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015,7,2
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015,7,2
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,98.0,0,1,Check-Out,2015-07-03,2015,7,3

In [43]:
#Week of year, day of week
data_df["res_week_of_year"] = data_df["reservation_status_date"].dt.isocalendar().week
data_df["res_day_of_week"] = data_df["reservation_status_date"].dt.dayofweek
data_df["res_weekday"] = data_df["reservation_status_date"].dt.day_name()
data_df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,reservation_status_year,reservation_status_month,reservation_status_day,res_week_of_year,res_day_of_week,res_weekday
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015,7,1,27,2,Wednesday
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015,7,1,27,2,Wednesday
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015,7,2,27,3,Thursday
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015,7,2,27,3,Thursday
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,98.0,0,1,Check-Out,2015-07-03,2015,7,3,27,4,Friday

In [44]:
##dropping the reservation status date feature
data_df.drop("reservation_status_date", inplace=True, axis=1)

In [45]:
#how many rows with adults?
(data_df["adults"] == 0).sum()

np.int64(380)

In [47]:
data_df.drop(data_df[data_df["adults"] == 0].index, inplace = True)

In [48]:
(data_df["adults"] == 0).sum()

np.int64(0)

In [51]:
#Dealing with Categorical (Non number) features.
#creating a new dataframe with jsut the categorical features from our original dataframe
cat_cols = [col for col in data_df.columns if data_df[col].dtype == "str"]
cat_cols

['hotel',
 'arrival_date_month',
 'meal',
 'country',
 'market_segment',
 'distribution_channel',
 'reserved_room_type',
 'assigned_room_type',
 'deposit_type',
 'customer_type',
 'reservation_status',
 'res_weekday']

In [52]:
cat_df = data_df[cat_cols]
cat_df.head()

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status,res_weekday
0,Resort Hotel,July,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out,Wednesday
1,Resort Hotel,July,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out,Wednesday
2,Resort Hotel,July,BB,GBR,Direct,Direct,A,C,No Deposit,Transient,Check-Out,Thursday
3,Resort Hotel,July,BB,GBR,Corporate,Corporate,A,A,No Deposit,Transient,Check-Out,Thursday
4,Resort Hotel,July,BB,GBR,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,Friday

In [53]:
#printing unique values of each column
for col in cat_df.columns:
    print(f"{col}: \n{cat_df[col].unique()}\n")

hotel:
<StringArray>
['Resort Hotel', 'City Hotel']
Length: 2, dtype: str

arrival_date_month:
<StringArray>
[     'July',    'August', 'September',   'October',  'November',  'December',
   'January',  'February',     'March',     'April',       'May',      'June']
Length: 12, dtype: str

meal:
<StringArray>
['BB', 'FB', 'HB', 'SC', 'Undefined']
Length: 5, dtype: str

country:
<StringArray>
['PRT', 'GBR', 'USA', 'ESP', 'IRL', 'FRA', 'ROU', 'NOR', 'OMN', 'ARG',
 ...
 'ATA', 'GTM', 'ASM', 'MRT', 'NCL', 'KIR', 'SDN', 'ATF', 'SLE', 'LAO']
Length: 177, dtype: str

market_segment:
<StringArray>
[       'Direct',     'Corporate',     'Online TA', 'Offline TA/TO',
 'Complementary',        'Groups',     'Undefined',      'Aviation']
Length: 8, dtype: str

distribution_channel:
<StringArray>
['Direct', 'Corporate', 'TA/TO', 'Undefined', 'GDS']
Length: 5, dtype: str

reserved_room_type:
<StringArray>
['C', 'A', 'D', 'E', 'G', 'F', 'H', 'L', 'B']
Length: 9, dtype: str

assigned_room_type:
<StringArray>
['C', 'A', 'D', 'E', 'G', 'F', 'I', 'B', 'H', 'L', 'K']
Length: 11, dtype: str

deposit_type:
<StringArray>
['No Deposit', 'Refundable', 'Non Refund']
Length: 3, dtype: str

customer_type:
<StringArray>
['Transient', 'Contract', 'Transient-Party', 'Group']
Length: 4, dtype: str

reservation_status:
<StringArray>
['Check-Out', 'Canceled', 'No-Show']
Length: 3, dtype: str

res_weekday:
<StringArray>
['Wednesday', 'Thursday', 'Friday', 'Tuesday', 'Sunday', 'Monday', 'Saturday']
Length: 7, dtype: str

In [55]:
#manually mapping arrival date month
cat_df["arrival_date_month"] = cat_df["arrival_date_month"].map({"January":1, "February":2, "March":3, "April":4, "May":5, "June":6, "July":7, "August": 8, "September":9, "October":10, "November":11, "December":12})

In [56]:
cat_df

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status,res_weekday
0,Resort Hotel,7,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out,Wednesday
1,Resort Hotel,7,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out,Wednesday
2,Resort Hotel,7,BB,GBR,Direct,Direct,A,C,No Deposit,Transient,Check-Out,Thursday
3,Resort Hotel,7,BB,GBR,Corporate,Corporate,A,A,No Deposit,Transient,Check-Out,Thursday
4,Resort Hotel,7,BB,GBR,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...
118897,City Hotel,8,BB,BEL,Offline TA/TO,TA/TO,A,A,No Deposit,Transient,Check-Out,Wednesday
118898,City Hotel,8,BB,FRA,Online TA,TA/TO,E,E,No Deposit,Transient,Check-Out,Thursday
118899,City Hotel,8,BB,DEU,Online TA,TA/TO,D,D,No Deposit,Transient,Check-Out,Thursday
118900,City Hotel,8,BB,GBR,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,Thursday
118901,City Hotel,8,HB,DEU,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,Thursday

In [59]:
#country and hotel features
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

#Label encode country
cat_df["country"] = le.fit_transform(cat_df["country"])

#Label encode hotel
cat_df["hotel"] = le.fit_transform(cat_df["hotel"])

In [60]:
cat_df

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status,res_weekday
0,1,7,BB,135,Direct,Direct,C,C,No Deposit,Transient,Check-Out,Wednesday
1,1,7,BB,135,Direct,Direct,C,C,No Deposit,Transient,Check-Out,Wednesday
2,1,7,BB,59,Direct,Direct,A,C,No Deposit,Transient,Check-Out,Thursday
3,1,7,BB,59,Corporate,Corporate,A,A,No Deposit,Transient,Check-Out,Thursday
4,1,7,BB,59,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...
118897,0,8,BB,15,Offline TA/TO,TA/TO,A,A,No Deposit,Transient,Check-Out,Wednesday
118898,0,8,BB,56,Online TA,TA/TO,E,E,No Deposit,Transient,Check-Out,Thursday
118899,0,8,BB,43,Online TA,TA/TO,D,D,No Deposit,Transient,Check-Out,Thursday
118900,0,8,BB,59,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,Thursday
118901,0,8,HB,43,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,Thursday

In [61]:
#one-hot encoding 
cat_df = pd.get_dummies(data = cat_df, columns = ["meal", "market_segment", "distribution_channel", "reserved_room_type", "assigned_room_type", "customer_type", "deposit_type", "reservation_status"])
cat_df.drop("res_weekday", inplace=True, axis=1)

In [62]:
cat_df

,hotel,arrival_date_month,country,meal_BB,meal_FB,meal_HB,meal_SC,meal_Undefined,market_segment_Aviation,market_segment_Complementary,market_segment_Corporate,market_segment_Direct,market_segment_Groups,market_segment_Offline TA/TO,market_segment_Online TA,market_segment_Undefined,distribution_channel_Corporate,distribution_channel_Direct,distribution_channel_GDS,distribution_channel_TA/TO,distribution_channel_Undefined,reserved_room_type_A,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,reserved_room_type_H,reserved_room_type_L,assigned_room_type_A,assigned_room_type_B,assigned_room_type_C,assigned_room_type_D,assigned_room_type_E,assigned_room_type_F,assigned_room_type_G,assigned_room_type_H,assigned_room_type_I,assigned_room_type_K,assigned_room_type_L,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,reservation_status_Canceled,reservation_status_Check-Out,reservation_status_No-Show
0,1,7,135,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
1,1,7,135,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
2,1,7,59,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
3,1,7,59,True,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
4,1,7,59,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118897,0,8,15,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
118898,0,8,56,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
118899,0,8,43,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
118900,0,8,59,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
118901,0,8,43,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False

In [65]:
#Numerical dataframe
num_df = data_df.drop(columns= cat_cols)

In [66]:
num_df

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_year,reservation_status_month,reservation_status_day,res_week_of_year,res_day_of_week
0,0,342,2015,27,1,0,0,2,0.0,0,0,0,0,3,NaN,0,0.00,0,0,2015,7,1,27,2
1,0,737,2015,27,1,0,0,2,0.0,0,0,0,0,4,NaN,0,0.00,0,0,2015,7,1,27,2
2,0,7,2015,27,1,0,1,1,0.0,0,0,0,0,0,NaN,0,75.00,0,0,2015,7,2,27,3
3,0,13,2015,27,1,0,1,1,0.0,0,0,0,0,0,304.0,0,75.00,0,0,2015,7,2,27,3
4,0,14,2015,27,1,0,2,2,0.0,0,0,0,0,0,240.0,0,98.00,0,1,2015,7,3,27,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118897,0,23,2017,35,30,2,5,2,0.0,0,0,0,0,0,394.0,0,96.14,0,0,2017,9,6,36,2
118898,0,102,2017,35,31,2,5,3,0.0,0,0,0,0,0,9.0,0,225.43,0,2,2017,9,7,36,3
118899,0,34,2017,35,31,2,5,2,0.0,0,0,0,0,0,9.0,0,157.71,0,4,2017,9,7,36,3
118900,0,109,2017,35,31,2,5,2,0.0,0,0,0,0,0,89.0,0,104.40,0,0,2017,9,7,36,3
118901,0,205,2017,35,29,2,7,2,0.0,0,0,0,0,0,9.0,0,151.20,0,2,2017,9,7,36,3

In [67]:
final_df = pd.concat([num_df, cat_df], axis=1)

In [68]:
final_df

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_year,reservation_status_month,reservation_status_day,res_week_of_year,res_day_of_week,hotel,arrival_date_month,country,meal_BB,meal_FB,meal_HB,meal_SC,meal_Undefined,market_segment_Aviation,market_segment_Complementary,market_segment_Corporate,market_segment_Direct,market_segment_Groups,market_segment_Offline TA/TO,market_segment_Online TA,market_segment_Undefined,distribution_channel_Corporate,distribution_channel_Direct,distribution_channel_GDS,distribution_channel_TA/TO,distribution_channel_Undefined,reserved_room_type_A,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,reserved_room_type_H,reserved_room_type_L,assigned_room_type_A,assigned_room_type_B,assigned_room_type_C,assigned_room_type_D,assigned_room_type_E,assigned_room_type_F,assigned_room_type_G,assigned_room_type_H,assigned_room_type_I,assigned_room_type_K,assigned_room_type_L,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,reservation_status_Canceled,reservation_status_Check-Out,reservation_status_No-Show
0,0,342,2015,27,1,0,0,2,0.0,0,0,0,0,3,NaN,0,0.00,0,0,2015,7,1,27,2,1,7,135,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
1,0,737,2015,27,1,0,0,2,0.0,0,0,0,0,4,NaN,0,0.00,0,0,2015,7,1,27,2,1,7,135,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
2,0,7,2015,27,1,0,1,1,0.0,0,0,0,0,0,NaN,0,75.00,0,0,2015,7,2,27,3,1,7,59,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
3,0,13,2015,27,1,0,1,1,0.0,0,0,0,0,0,304.0,0,75.00,0,0,2015,7,2,27,3,1,7,59,True,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
4,0,14,2015,27,1,0,2,2,0.0,0,0,0,0,0,240.0,0,98.00,0,1,2015,7,3,27,4,1,7,59,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118897,0,23,2017,35,30,2,5,2,0.0,0,0,0,0,0,394.0,0,96.14,0,0,2017,9,6,36,2,0,8,15,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
118898,0,102,2017,35,31,2,5,3,0.0,0,0,0,0,0,9.0,0,225.43,0,2,2017,9,7,36,3,0,8,56,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
118899,0,34,2017,35,31,2,5,2,0.0,0,0,0,0,0,9.0,0,157.71,0,4,2017,9,7,36,3,0,8,43,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
118900,0,109,2017,35,31,2,5,2,0.0,0,0,0,0,0,89.0,0,104.40,0,0,2017,9,7,36,3,0,8,59,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
118901,0,205,2017,35,29,2,7,2,0.0,0,0,0,0,0,9.0,0,151.20,0,2,2017,9,7,36,3,0,8,43,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False

In [71]:
#Correlation analysis
#create a correlation matrix
corr_matrix = final_df.corr().abs()
corr_matrix

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_year,reservation_status_month,reservation_status_day,res_week_of_year,res_day_of_week,hotel,arrival_date_month,country,meal_BB,meal_FB,meal_HB,meal_SC,meal_Undefined,market_segment_Aviation,market_segment_Complementary,market_segment_Corporate,market_segment_Direct,market_segment_Groups,market_segment_Offline TA/TO,market_segment_Online TA,market_segment_Undefined,distribution_channel_Corporate,distribution_channel_Direct,distribution_channel_GDS,distribution_channel_TA/TO,distribution_channel_Undefined,reserved_room_type_A,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,reserved_room_type_H,reserved_room_type_L,assigned_room_type_A,assigned_room_type_B,assigned_room_type_C,assigned_room_type_D,assigned_room_type_E,assigned_room_type_F,assigned_room_type_G,assigned_room_type_H,assigned_room_type_I,assigned_room_type_K,assigned_room_type_L,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,reservation_status_Canceled,reservation_status_Check-Out,reservation_status_No-Show
is_canceled,1.000000,0.182933,0.087449,0.001180,0.005381,0.060386,0.083838,0.081074,0.066124,0.020744,0.089305,0.050999,0.050608,0.093669,0.043246,0.004578,0.125962,0.184113,0.122370,0.009340,0.099776,0.011826,0.104362,0.122361,0.069262,0.003420,0.097385,0.039691,0.000160,0.004387,0.061847,0.018203,0.008811,0.030720,0.075168,0.112626,0.002860,0.124466,0.210774,0.007783,0.079974,0.118183,0.007906,0.149952,0.008907,0.044359,0.005323,0.011108,0.028686,0.001508,0.010914,0.029534,0.024513,0.001066,0.074359,0.024815,0.032891,0.042519,0.026115,0.013309,0.010418,0.015896,0.037137,0.022427,0.005504,0.048876,0.031168,0.128014,0.109269,0.156617,0.165237,0.002606,0.970963,1.000000,0.175584
lead_time,0.182933,1.000000,0.138387,0.101223,0.009439,0.235428,0.312606,0.141754,0.022918,0.003702,0.146763,0.005628,0.076486,0.080710,0.025703,0.132260,0.018432,0.085673,0.032062,0.076291,0.057707,0.001008,0.053913,0.025164,0.037349,0.106253,0.095810,0.064420,0.013080,0.138679,0.054920,0.008200,0.045107,0.069017,0.162540,0.141971,0.193578,0.132007,0.004427,0.004394,0.129726,0.132654,0.031939,0.193995,0.005049,0.024460,0.033427,0.001647,0.016797,0.025993,0.025027,0.000036,0.001893,0.007756,0.041851,0.014206,0.004921,0.039835,0.011599,0.030116,0.008252,0.005195,0.008984,0.019815,0.003166,0.065756,0.025530,0.162580,0.151732,0.168096,0.167832,0.026667,0.193604,0.182933,0.033650
arrival_date_year,0.087449,0.138387,1.000000,0.513891,0.009932,0.005044,0.003834,0.037800,0.042053,0.023090,0.024346,0.054025,0.028222,0.009169,0.020022,0.027753,0.176448,0.038919,0.064083,0.959861,0.418558,0.009800,0.445193,0.005554,0.077939,0.499462,0.130414,0.075154,0.030937,0.014351,0.117270,0.015874,0.018841,0.018670,0.035283,0.013179,0.060272,0.108291,0.134863,0.008488,0.035708,0.025056,0.016086,0.040770,0.013421,0.056915,0.037962,0.017394,0.049397,0.020975,0.010392,0.014122,0.000758,0.014702,0.020369,0.059257,0.000346,0.001145,0.004175,0.007263,0.003083,0.004830,0.004667,0.006125,0.006002,0.168153,0.017444,0.170529,0.094544,0.018924,0.019296,0.001758,0.091509,0.087449,0.011802
arrival_date_week_number,0.001180,0.101223,0.513891,1.000000,0.092946,0.026872,0.028235,0.025066,0.013653,0.013597,0.038601,0.006453,0.020898,0.012378,0.018117,0.013215,0.098556,0.008868,0.046004,0.461224,0.802035,0.031997,0.824767,0.019180,0.019122,0.995061,0.023499,0.004374,0.012382,0.033360,0.038739,0.010381,0.006710,0.011887,0.005950,0.009963,0.013235,0.042273,0.029762,0.001818,0.015207,0.005800,0.003553,0.003237,0.002541,0.008416,0.010436,0.009255,0.001155,0.002820,0.007851,0.001858,0.007826,0.001827,0.008954,0.017753,0.010471,0.007936,0.001483,0.007374,0.005959,0.011371,0.004058,0.005535,0.000538,0.091170,0.013617,0.059934,0.013904,0.000519,0.003975,0.013992,0.005788,0.001180,0.018897
arrival_date_day_of_month,0.005381,0.009439,0.009932,0.092946,1.000000,0.017182,0.027836,0.000607,0.014892,0.000594,0.004738,0.008761,0.000689,0.007139,0.009265,0.006116,0.022640,0.008680,0.002002,0.013696,0.002055,0.335898,0.047585,0.005521,0.009030,0.000076,0.005882,0.008802,0.002996,0.002357,0.011408,0.005521,0.001288,0.005004,0.004100,0.004987,0.008445,0.001018,0.005339,0.006428,0.012224,0.009771,0.001620,0.001254,0.008272,0.019124,0.004797,0.001070,0.008277,0.010573,0.008963,0.005211,0.002800,0.004695,0.013517,0.004878,0.001045,0.003013,0.009522,0.008009,0.003001,0.002998,0.003333,0.005913,0.000456,0.019189,0.000959,0.004972,0.005188,0.011670,0.003034,0.028535,0.004592,0.005381,0.003547
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
deposit_type_Non Refund,0.165237,0.167832,0.019296,0.003975,0.003034,0.029650,0.031979,0.031208,0.031005,0.010507,0.016078,0.090529,0.001774,0.028286,0.021511,0.112604,0.028904,0.032449,0.090392,0.067777,0.009148,0.002162,0.008914,0.042328,0.045439,0.004036,0.109584,0.016335,0.024233,0.010278,0.037381,0.001636,0.005634,0.009842,0.008020,0.040191,0.275293,0.034903,0.128916,0.000529,0.014504,0.029917,0.005041,0.018538,0.000837,0.064774,0.007227,0.010330,0.049294,0.011645,0.019575,0.016399,0.006601,0.000917,0.080431,0.007458,0.011372,0.056775,0.015973,0.019243,0.018276,0.007589,0.005306,0.005096,0.000374,0.005427,0.008676,0.001012,0.003841,0.951491,1.000000,0.003874,0.168947,0.165237,0.005996
deposit_type_Refundable,0.002606,0.026667,0.001758,0.013992,0.028535,0.002160,0.003215,0.001012,0.006914,0.003357,0.000259,0.002877,0.003049,0.023708,0.016450,0.023663,0.017241,0.012930,0.021270,0.002493,0.006991,0.018616,0.009408,0.010561,0.034142,0.017117,0.002149,0.014094,0.002274,0.008795,0.009098,0.002649,0.001800,0.003144,0.003071,0.008045,0.105002,0.011746,0.033062,0.000169,0.004326,0.041942,0.001610,0.034114,0.000267,0.014249,0.003379,0.012460,0.011864,0.004420,0.004591,0.005463,0.002929,0.000293,0.003318,0.002460,0.028286,0.009416,0.003822,0.005691,0.006042,0.003181,0.002232,0.001628,0.000120,0.003299,0.018223,0.062282,0.067320,0.303989,0.003874,1.000000,0.002460,0.002606,0.000747
reservation_status_Canceled,0.970963,0.193604,0.091509,0.005788,0.004592,0.058112,0.082611,0.089174,0.067113,0.020125,0.091195,0.053424,0.050518,0.094243,0.039836,0.006615,0.131154,0.178767,0.120441,0.011451,0.098117,0.013038,0.102531,0.124916,0.063354,0.008362,0.085887,0.041749,0.000494,0.000018,0.060087,0.017166,0.013229,0.032033,0.078599,0.117486,0.000506,0.127189,0.217227,0.008016,0.083933,0.123096,0.008528,0.156581,0.009228,0.047402,0.005173,0.011929,0.030622,0.000734,0.010423,0.032474,0.025140,0.001300,0.074195,0.025352,0.033025,0.042037,0.026205,0.015204,0.012416,0.016159,0.036801,0.022648,0.005668,0.047941,0.030855,0.127890,0.109716,0.160196,0.168947,0.002460,1.000000,0.970963,0.065027
reservation_status_Check-Out,1.000000,0.182933,0.087449,0.001180,0.005381,0.060386,0.083838,0.081074,0.066124,0.020744,0.089305,0.050999,0.050608,0.093669,0.043246,0.004578,0.125962,0.184113,0.122370,0.009340,0.099776,0.011826,0.104362,0.122361,0.069262,0.003420,0.097385,0.039691,0.000160,0.004387,0.061847,0.018203,0.008811,0.030720,0.075168,0.112626,0.002860,0.124466,0.210774,0.007783,0.079974,0.118183,0.007906,0.149952,0.008907,0.044359,0.005323,0.011108,0.028686,0.001508,0.010914,0.029534,0.024513,0.001066,0.074359,0.024815,0.032891,0.042519,0.026115,0.013309,0.010418,0.015896,0.037137,0.022427,0.005504,0.048876,0.031168,0.128014,0.109269,0.156617,0.165237,0.002606,0.970963,1.000000,0.175584
reservation_status_No-Show,0.175584,0.033650,0.011802,0.018897,0.003547,0.012746,0.009751,0.028787,0.000360,0.003710,0.002768,0.007119,0.003210,0.002894,0.016870,0.008124,0.014298,0.032327,0.014805,0.008165,0.012423,0.004324,0.013388,0.003648,0.028201,0.020148,0.052775,0.006244,0.001367,0.018374,0.010712,0.005286,0.017687,0.003680,0.009903,0.013684,0.009848,0.004224,0.014731,0.000521,0.011802,0.013587,0.002115,0.018867,0.000824,0.010035,0.000914,0.002755,0.006359,0.003268,0.002633,0.010441,0.001208,0.000903,0.004845,0.000818,0.001292,0.004369,0.001093,0.007054,0.007640,0.000191,0.003468,0.000350,0.000369,0.006592,0.003037,0.007689,0.004288,0.005943,0.005996,0.000747,0.065027,0.175584,1.000000

In [72]:
#setting the threshold
threshold = 0.85

In [73]:
import numpy as np
#This is taking the matrix and removing the diagonal cells and the triangle of cells below that since the diagonals
#are always going to be one since they are comparing to themselves, and the cells below that are a mirror of the
#cells above it. This sets these cells to NaN.
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

In [74]:
#ensure only 1 of highly correlated features get dropped. 
to_drop = []
for i in range(len(corr_matrix.columns)):
    for j in range(i):
        if abs(corr_matrix.iloc[i,j]) >= threshold:
            colname = corr_matrix.columns[i]
            to_drop.append(colname)

In [75]:
to_drop

['reservation_status_year',
 'res_week_of_year',
 'arrival_date_month',
 'distribution_channel_Direct',
 'assigned_room_type_G',
 'assigned_room_type_H',
 'deposit_type_Non Refund',
 'reservation_status_Canceled',
 'reservation_status_Check-Out',
 'reservation_status_Check-Out']

In [76]:
#Drop those columns
final_df.drop(columns=to_drop, inplace=True)

In [77]:
#should we drop agent feature?
final_df.agent.isnull().sum()

np.int64(11800)

In [78]:
#ideally look up more info about these agents. In this case null is "not applicable". Keep column.
#imputing with 0

final_df["agent"] = final_df["agent"].fillna(0)

In [79]:
final_df

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_month,reservation_status_day,res_day_of_week,hotel,country,meal_BB,meal_FB,meal_HB,meal_SC,meal_Undefined,market_segment_Aviation,market_segment_Complementary,market_segment_Corporate,market_segment_Direct,market_segment_Groups,market_segment_Offline TA/TO,market_segment_Online TA,market_segment_Undefined,distribution_channel_Corporate,distribution_channel_GDS,distribution_channel_TA/TO,distribution_channel_Undefined,reserved_room_type_A,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,reserved_room_type_H,reserved_room_type_L,assigned_room_type_A,assigned_room_type_B,assigned_room_type_C,assigned_room_type_D,assigned_room_type_E,assigned_room_type_F,assigned_room_type_I,assigned_room_type_K,assigned_room_type_L,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,deposit_type_No Deposit,deposit_type_Refundable,reservation_status_No-Show
0,0,342,2015,27,1,0,0,2,0.0,0,0,0,0,3,0.0,0,0.00,0,0,7,1,2,1,135,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,True,False,False
1,0,737,2015,27,1,0,0,2,0.0,0,0,0,0,4,0.0,0,0.00,0,0,7,1,2,1,135,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,True,False,False
2,0,7,2015,27,1,0,1,1,0.0,0,0,0,0,0,0.0,0,75.00,0,0,7,2,3,1,59,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,True,False,False
3,0,13,2015,27,1,0,1,1,0.0,0,0,0,0,0,304.0,0,75.00,0,0,7,2,3,1,59,True,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False
4,0,14,2015,27,1,0,2,2,0.0,0,0,0,0,0,240.0,0,98.00,0,1,7,3,4,1,59,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118897,0,23,2017,35,30,2,5,2,0.0,0,0,0,0,0,394.0,0,96.14,0,0,9,6,2,0,15,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False
118898,0,102,2017,35,31,2,5,3,0.0,0,0,0,0,0,9.0,0,225.43,0,2,9,7,3,0,56,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,True,False,False
118899,0,34,2017,35,31,2,5,2,0.0,0,0,0,0,0,9.0,0,157.71,0,4,9,7,3,0,43,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,True,False,False
118900,0,109,2017,35,31,2,5,2,0.0,0,0,0,0,0,89.0,0,104.40,0,0,9,7,3,0,59,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False
118901,0,205,2017,35,29,2,7,2,0.0,0,0,0,0,0,9.0,0,151.20,0,2,9,7,3,0,43,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False